language: bash
script:
- common/travis/checkFileName.sh
after_success:
- common/travis/push.sh
env:
  global:
    secure: Ch82PZI3INJ3CI9ICIVMihk3SiVu9Gqes/0dY+7dBUDHro1lBNBCd8ODXecc3HrP07nRpG5wmFrEf9342IURhBDBfIxfzKe/ZMKxbLjw+SPeLlwiSCzeAIsM+KeQ1W99FBnuZa7FlMUfFFoq733vd36lLw0GfiwJbFh/U54W8ehigjvm+XSPtovUVmmBNicdVjoJkui5KyUC9sBBUA8juYBdTUI1gJC/d1Jh/2V0BkwqMUtZZVEFAo1higWSV2D2gTDuN5gh7UFqfQ6HullrzgknAc9BRxKHLotDygpzVG3cAguBg2RvkQ75UprOT5FfSKHP1YbPFSTbadAq1zz1sIkbIOo1LsDaLfFCGidli0i/Z3BVTtVNlw+TxgQFSQVRJiJ+qOi7dR0Pg5PisBiyCokITc8cU6DydXGD6RqlrPhv09JOsVT5NAwm1drVfPMnuwg+kdEFmlNAY+8SGanvysl/7yfeG/2ykztqerQA4tScHxc3wYVzGT9KYvKgCAosjW7V9Y7rc9h1tBDOUYepteecBE61jPf6ivaXg8wytIMnWNqS1D5zg+edeNjm/ZpbGjQ4AfREovyMnAYPvNPyom/0KuyJNqxKD+GI0EX6QB+TIT+A+SvvECdNtBPdwPS/miyW8aUG1Nm+NuWj+HBEhnFcQ9Ahq0162EkSstMgFw4=
